### ISSUE TITLE
Some services shouldn't be disabled

### ISSUE THREAD

**Issue by Zeioth** [achadwick/gsdwacom4xfce#4]
If I run "gnome-control-center wacom -v" and try to resize the active zone, the settings closed and I recieve an error saying that I must enable the applet "org.gnome.Mutter.DisplayConfig"

Also I'll add a --gnome-fix parameter to gsdplugins.sh to allow gnome users to keep enabled all applets in case they use gnome as secondary desktop environment.

**Comment by achadwick** [comment]
Thanks for the offer of work on this, and #1, #2 and #3. Patches very welcome indeed!

Also, I just discovered that we can now assign issues to either reporters or thread participants (not sure which), so I've passed these bugs on to you. 

<small>It's probably fairly obvious that I'm not an Xfce4 user right now, given this project's general state of disrepair. I should hand this project over to someone, really.</small>

**Comment by Zeioth** [comment]
Sorry for the delay! I already fixed #1, #2 and #3 so I will push soon.

My intention is to bring the project to a state where, with minimun effort, can be used by the XFCE team to integrate it natively. I don't know if this is possible, but I'm going to try.

If you like my code, I offer myself to continue the project.

**Comment by Zeioth** [comment]
It's working! I've uploaded the [new repo here](https://github.com/Zeioth/XFCE-Wacom-Settings).

The next weeks/months I'll be working on native integration.

**Comment by achadwick** [comment]
Sounds like an awesome project. Thank you for taking this over, and I'll update the README.
